version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: foodly-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-foodly_db}
      POSTGRES_USER: ${POSTGRES_USER:-ayushagarwal}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ayush1}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    networks:
      - foodly-network
    restart: unless-stopped

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: foodly-backend
    environment:
      - SPRING_APPLICATION_NAME=foodly-backend
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB:-foodly_db}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER:-ayushagarwal}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD:-ayush1}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=false
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=false
      - SERVER_PORT=8080
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-change-this-in-production}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-86400000}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://localhost:3000,http://localhost:80}
      - SPRING_PROFILES_ACTIVE=production
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - foodly-network
    restart: unless-stopped

  # Frontend Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL:-http://localhost:8080}
    container_name: foodly-frontend
    environment:
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL:-http://localhost:8080}
      - REACT_APP_ENVIRONMENT=${REACT_APP_ENVIRONMENT:-production}
      - REACT_APP_VERSION=${REACT_APP_VERSION:-1.0.0}
      - REACT_APP_ENABLE_ANALYTICS=${REACT_APP_ENABLE_ANALYTICS:-true}
      - REACT_APP_ENABLE_NOTIFICATIONS=${REACT_APP_ENABLE_NOTIFICATIONS:-true}
      - REACT_APP_APP_NAME=${REACT_APP_APP_NAME:-Foodly}
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - foodly-network
    restart: unless-stopped

  # Nginx Reverse Proxy (Optional - for production)
  nginx:
    image: nginx:alpine
    container_name: foodly-nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - foodly-network
    restart: unless-stopped
    profiles:
      - production

volumes:
  postgres_data:

networks:
  foodly-network:
    driver: bridge 